export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

//profile
export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED ";

//search
export const GET_SEARCH = "GET_SEARCH";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const CLEAR_SEARCH = "CLEAR_SEARCH";
export const AUTO_SUGGESTION = "AUTO_SUGGESTION";

//user request
export const POST_USER_REQUEST= "POST_USER_REQUEST";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const USER_REQUEST_ERROR = "USER_REQUEST_ERROR";
export const CLEAR_USER_REQUEST = "CLEAR_USER_REQUEST";

//peer request
export const CHECK_NEW_PEER_REQUEST = "CHECK_NEW_PEER_REQUEST";
export const PEER_REQUEST_ERROR = "PEER_REQUEST_ERROR";

//tutor matches
export const GET_TUTOR_REQUESTS = "GET_TUTOR_REQUESTS";
export const TUTOR_REQUESTS_ERROR = "TUTOR_REQUESTS_ERROR";